language: node_js
node_js: stable
cache:
  directories:
    - node_modules
branches:
  only:
    - dev
install:
  - yarn
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: dev
  local-dir: public
